version: '3'

services:
  es:
    image: elasticsearch:6.6.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - es


