# Generated by Django 2.1.15 on 2023-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('sandns', models.TextField()),
                ('sanip', models.TextField()),
                ('selfsigned', models.CharField(max_length=10)),
            ],
        ),
    ]
